version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventori
      - DB_USERNAME=inventori_user
      - DB_PASSWORD=inventori_password

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inventori
      MYSQL_USER: inventori_user
      MYSQL_PASSWORD: inventori_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge